name: Feedback
description: Provide feedback to the maintainer.

body:
  - type: markdown
    attributes:
      value: "## Thank you for providing feedback!"
  - type: markdown
    attributes:
      value: Please complete this form to submit your feedback.
      
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: Please provide your feedback to the maintainer.
      placeholder: Enter your feedback here.
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Does your feedback relate to code, file/folder structure, files, and/or something else?
      multiple: true
      options:
        - Code
        - File/folder structure
        - Files
        - Other
